### ISSUE TITLE
All- imp -question-of-binarytree

### ISSUE THREAD

**Issue by SHOBHA-0502** [Dipak3007/Hacktoberfest#24]
I want to add all the important and famous questions about binary trees which help me to crack the interview at Microsoft.

@Dipak3007  kindly assign this issue to me in hactoberfest 2022.

**Comment by Manishgupta200** [comment]
I want to add. Assign it to me

**Comment by Dipak3007** [comment]
You're free to add any algorithm.
Happy Hacking!
