### ISSUE TITLE
I will like to add important questions from stacks and Queues. 

### ISSUE THREAD

**Issue by ritikanagar09** [Dipak3007/Hacktoberfest#50]
These would be the most important from stack and Queues. These will be sorted in the form of easy to hard. Including for which company that question is famous for.

**Comment by Dipak3007** [comment]
You're free to add anything you want.
Happy hacking!

**Comment by ritikanagar09** [comment]
Thanks for assigning this to me.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
10/23/22,
01:11:13 AM
